name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: corepack enable
      - name: Cache Yarn
        uses: actions/cache@v6
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Generate coverage
        run: yarn c8 --config c8.config.json --reporter=lcov --reporter=text yarn test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage/lcov.info
